### ISSUE TITLE
MIME type "audio/mpeg3"

### ISSUE THREAD

**Issue by seabrus** [jalik/jalik-ufs#89] opened 2016-09-23 19:26 UTC
Hi @jalik,

With `UFS v0.6.9` I upload audio files with mp3 extention and MIME type `audio/mpeg` (as the browser detected it). Although I explicitly set it in the `UploadFS.Uploader`:
```javascript
let fileObj = {
    name: newFile.name,
    size: newFile.size,
    type: newFile.type,
    ...
  };

  const ONE_MB = 1024 * 1000;
  let uploader = new UploadFS.Uploader({
    file: fileObj, 
    ...
```
when I check the DB I find that the MIME type for my file is set to `audio/mpeg3`. `UploadFS.getMimeTypes()` also contains `mp3: audio/mpeg3` setting. 

The problem is that Firefox 48 and Chromium 52 (and earlier versions too) do not play files with the extension `audio/mpeg3` (as well as `audio/x-mpeg-3`) in the HTML5 `audio` element: 
```javascript
<audio controls>
    <source src="file.mp3" type="audio/mpeg3">
    <img src="img/dummy.png" alt="Can not play the audio file">
</audio>
```
Googling the web, I found statements that although `audio/mpeg3` is mentioned in some MIME type lists (for example, [this](https://www.sitepoint.com/web-foundations/mime-types-complete-list/)), nevertheless
> `audio/mpeg3` does not appear to be a valid registered mime type. Seems like the mime type returned for `mp3` files should instead be [audio/mpeg](https://tools.ietf.org/html/rfc3003)

 --- also see [here](https://groups.google.com/d/msg/jplayer/yTOQIy2x0jo/Wn_Mv2GTJYoJ), [here](http://stackoverflow.com/questions/10688588/which-mime-type-should-i-use-for-mp3), [here](https://github.com/NancyFx/Nancy/issues/1589), etc.

Another quite popular and supporrted by FF and Chrome extension is `audio/mp3`. 

IMHO, it would be more flexible and universal to set `mp3: audio/mpeg` in MIME types. What do you think about all that?

Have a nice day

**Comment by jalik** [comment] 2016-09-23 19:37
I agree with you, MIME type detection is a new feature and needs some time to be better.
It is fixed in the `v0.6.9_1`.
Thanks for your help.

**Closed by jalik** 2016-09-23 19:37 UTC

**Comment by seabrus** [comment] 2016-09-23 19:56
Thank you for your prompt reply!

By the way, `ogg` is an increasingly popular audio format, not only `application/ogg`: `audio/ogg` and `audio/oga`. To resolve such contradictions and take into account the MIME types variety, it could be better to provide precedence of the type that is set by a programmer in the `UploadFS.Uploader`. 

BTW, in the doc you write 
> So when uploading a file, if the file.type is not set, UploadFS will check in its MIME list and assign the corresponding MIME, you can also add your own MIME types.

but in my case this did not work and the MIME type from the new MIME module (not from my code) was set. Maybe I should set the type in another place, not in the `UploadFS.Uploader`?

**Comment by jalik** [comment] 2016-09-23 20:19
@seabrus yes I fixed this in the last version, I forgot to add a condition to check if UploadFS should auto-detect MIME type when not defined, or ignore if defined, it's working as intended.

Also thanks to mention OGG, I totally forgot to add it.
